Bahmni/bahmni-package

bahmni-emr/build.gradle
JIRA link : https://bahmni.atlassian.net/browse/BAH-520
=> BAH-520: Included Reporting Rest and Operation theater in the build.gradle

bahmni-web/resources/httpd.conf, bahmni-web/resources/ssl.conf
https://bahmni.atlassian.net/browse/BAH-632
=> Shilpa|BAH-632|Made httpd 2.4 service running

bahmni-web/resources/httpd.conf
https://bahmni.atlassian.net/browse/BAH-632
=> Shilpa|BAH-632|Upgrading apache to 2.4

bahmni-emr/scripts/preuninstall.sh, bahmni-erp-connect/scripts/preuninstall.sh, bahmni-erp/scripts/preuninstall.sh, bahmni-event-log-service/scripts/preuninstall.sh, bahmni-lab/scripts/preuninstall.sh, bahmni-pacs/scripts/dcm4chee/preuninstall.sh, bahmni-pacs/scripts/pacs-integration/preuninstall.sh, bahmni-reports/scripts/preuninstall.sh
https://bahmni.atlassian.net/browse/BAH-641
=> Shilpa|BAH-641|Replacing service with systemctl in all sh files

bahmni-installer/build.gradle
https://bahmni.atlassian.net/browse/BAH-704
=> Shilpa|BAH-704|Bahmni installer should install bahmni command

bahmni-erp/build.gradle, bahmni-erp/scripts/postinstall.sh, bahmni-erp/scripts/preinstall.sh, bahmni-erp/scripts/preuninstall.sh, bahmni-erp/scripts/rpm/odoo
Upgraded Bahmni ERP scripts to work with Odoo 10 integration. Removed unwanted code related o placeholder and dump files.
=> Odoo integration

bahmni-emr/scripts/rpm/openmrs
create symlink to openmrs-runtime.properties, move out of the if condition
=> BAH-848 | create symlink to openmrs-runtime.properties

bahmni-lab/resources/hibernate.cfg.xml
Closed OLD PR 27 and created new one
=> BAH-981 - Changes for Liquibase for new tables

bahmni-emr/scripts/openmrs.service, bahmni-emr/scripts/postinstall.sh, bahmni-erp-connect/scripts/bahmni-erp-connect.service, bahmni-erp-connect/scripts/postinstall.sh, bahmni-event-log-service/scripts/bahmni-event-log-service.service, bahmni-event-log-service/scripts/postinstall.sh, bahmni-lab/scripts/bahmni-lab.service, bahmni-lab/scripts/postinstall.sh, bahmni-pacs/scripts/dcm4chee/postinstall.sh, bahmni-pacs/scripts/pacs-integration.service, bahmni-pacs/scripts/pacs-integration/postinstall.sh, bahmni-reports/scripts/bahmni-reports.service, bahmni-reports/scripts/postinstall.sh
https://bahmni.atlassian.net/browse/BAH-1181
=> Bindu | BAH-1181 | Running service command should redirect to systemctl command instead of starting services with service command

bahmni-installer/scripts/preinstall.sh
Reverts Bahmni/bahmni-package#41
=> Revert "Buvaneswari|CI failure fix" - Fix in the wrong place - Issue still exists

bahmni-docker/docker-compose.yml
This PR removes duplicate code from docker-compose.yml
=> BAH-1298 | Fix | Removed duplicated code

bahmni-docker/README.md
Updated Readme for Odoo sync issues for old patient data. Also did some minor improvements to readme.md.
=> BAH-1310|Gurpreet|Updated README to explain steps to fix Odoo sync issue

bahmni-docker/.env, bahmni-docker/README.md, bahmni-docker/docker-compose.yml
This PR updates the bahmni-web development steps which allows hot reloading of changes without the need for building the code.
=> BAH-1314| Mohan | Refactor | Bahmni-web development steps

.github/workflows/ci.yml, bahmni-docker/README.md
Co-authored-by: swatigogia2020 <swati.gogia@thoughtworks.com>
=> BAH-1393 | Removed v0.94 from CI

bahmni-proxy/resources/bahmni-proxy.conf
Updating context root for Lab-Lite
=> Bahmni-Lab Issue - Update bahmni-proxy.conf

bahmni-proxy/resources/bahmni-proxy.conf, bahmni-proxy/resources/index.html
Co-authored-by: stavtnameh <hemanth.v@beehyv.com>
=> BAH-1816 | Added tags for disabling search engine crawling

bahmni-lab/scripts/postinstall.sh
JIRA card [https://bahmni.atlassian.net/browse/BAH-1872](https://bahmni.atlassian.net/browse/BAH-1872)
=> Bindu | BAH-1872 | fix permission issue with elis folder in uploaded-files

.github/workflows/dcm4chee_build_publish.yml, bahmni-docker/docker-compose.yml, bahmni-pacs/docker/dcm4chee/Dockerfile, bahmni-pacs/docker/dcm4chee/scripts/startup.sh, bahmni-pacs/docker/dcm4chee/templates/pacs-postgres-ds.xml.template
This PR adds dockerisation for dcm4chee and Oviyam. Also a Github Action is added to build and publish `bahmni/dcm4chee` docker image.
=> BAH-2054 | Dockerisation and Github Actions for DCM4CHEE

bahmni-docker/docker-compose.yml
This pr adds the volume mount for persisting forms created from implementer-interface.
=> BAH-2163 | Added Volume Mount for clinical forms

bahmni-docker/docker-compose.yml
Co-authored-by: MOHANKUMAR T <mohan13081999@gmail.com>
Co-authored-by: Tuhin <tuhin.s@beehyv.com>
=> BAH-2035|Fixed image storage problem

bahmni-proxy/README.md, bahmni-proxy/resources/bahmni-proxy.conf
Added the rule in Bahmni proxy configuration file  to pass a request to the speech assistant application.
=> BAH-1904 | Integrate Speech Assistant Application with Bahmni

.github/trivy_scan.sh, .github/workflows/trivy_scan.yaml
This PR changes Trivy's Brew based installation to manual installation
=> BAH-2366 | Remove Trivy Brew based Installation

bahmni-proxy/resources/index.html
Jira link: https://bahmni.atlassian.net/browse/BAH-2284?atlOrigin=eyJpIjoiOGVjNmJjMjM5OWJlNDNiNDg4MjU5ZjBhNzY2NDBkMjQiLCJwIjoiaiJ9
Screenshot of Landing page:
=> BAH-2284 | Refactor. Landing page to display apps based on configuration

bahmni-emr/resources/web.xml, bahmni-erp-connect/resources/log4j2.xml
Talk thread Link:https://talk.openmrs.org/t/logging-not-working-in-bahmni-erp-connect-0-93/42872
=> Deepthi M|BAH-3977|Updated log4j2.xml file and removed log4j listener as its no longer required with log4j2.

.github/workflows/atomfeed_console_build_publish.yaml
JIRA -> [BAH-4097](https://bahmni.atlassian.net/browse/BAH-4097)
For Standard Release.
=> BAH-4097 | Add. appVersionFile Path To atomfeed-console Workflow
